### ISSUE TITLE
Formatting issue in roxygen manual

### ISSUE THREAD

**Issue by MichaelChirico** [ewenme/ghibli#2]
![screen shot 2018-07-26 at 10 30 06 am](https://user-images.githubusercontent.com/7606389/43238016-ec59dc4e-90be-11e8-9b19-c795f3b17be3.png)

From `?ghibli_palette`, we see something from the `roxygen` markup didn't parse correctly and ended up in the manual here.

**Comment by ewenme** [comment]
I've fixed this in the latest development version (and 0.1.2 - winging it's way to CRAN). Thanks!
